//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ply614.rc
//
#define IDOK                            1
#define IDCANCEL                        2
#define IDD_SYSTEM_PAGE                 200
#define IDD_CAMERA_PAGE                 201
#define IDD_SENSOR_PAGE                 202
#define IDD_DVRSTATUS_PAGE              203
#define IDD_DIALOG_FILEPASSWORD         206
#define IDC_SERVERNAME                  1000
#define IDC_SHUTDOWNDELAY               1001
#define IDC_CAMERANUMBER                1002
#define IDC_SENSORNUMBER                1003
#define IDC_ALARMNUMBER                 1004
#define IDC_IOMODULE                    1005
#define IDC_DVRUSERMAN                  1006
#define IDC_BREAKBYSIZE                 1007
#define IDC_BREAKSIZE                   1008
#define IDC_BREAKBYTIME                 1009
#define IDC_BREAKTIME                   1010
#define IDC_AUTODISK                    1011
#define IDC_MINDISKSPACE                1012
#define IDC_VIDEO_ENCRYPT               1013
#define IDC_EDIT_VIDEOPASSWORD          1014
#define IDC_EVENTMARKER                 1015
#define IDC_EVMPRELOCK                  1016
#define IDC_EVMPOSTLOCK                 1017
#define IDC_PTZ_ENABLE                  1018
#define IDC_PTZ_PORT                    1019
#define IDC_PTZ_BAUDRATE                1020
#define IDC_PTZ_PROTOCOL                1021
#define IDC_TAB_CAMERA                  1022
#define IDC_CAMENABLE                   1023
#define IDC_NAME                        1024
#define IDC_PICTUREFORMAT               1025
#define IDC_RECORDMODE                  1026
#define IDC_QUALITY                     1027
#define IDC_FRAMERATE                   1028
#define IDC_ENABLE_BITRATE              1029
#define IDC_VBR                         1030
#define IDC_CBR                         1031
#define IDC_BITRATE                     1032
#define IDC_TRIGPORT1                   1033
#define IDC_TRIGEN1                     1034
#define IDC_TRIGOSD1                    1035
#define IDC_TRIGPORT2                   1036
#define IDC_TRIGEN2                     1037
#define IDC_TRIGOSD2                    1038
#define IDC_TRIGPORT3                   1039
#define IDC_TRIGEN3                     1040
#define IDC_TRIGOSD3                    1041
#define IDC_TRIGPORT4                   1042
#define IDC_TRIGEN4                     1043
#define IDC_TRIGOSD4                    1044
#define IDC_PREREC                      1045
#define IDC_POSTREC                     1046
#define IDC_GPSBOX                      1047
#define IDC_GPS                         1048
#define IDC_GPSENGLISH                  1049
#define IDC_GPSMETRIC                   1050
#define IDC_ALARMREC                    1051
#define IDC_ALARMRECPORT                1052
#define IDC_ALARMRECPAT                 1053
#define IDC_ALARMVIDEOLOST              1054
#define IDC_ALARMVIDEOLOSTPORT          1055
#define IDC_ALARMVIDEOLOSTPAT           1056
#define IDC_ALARMMOTION                 1057
#define IDC_ALARMMOTIONPORT             1058
#define IDC_ALARMMOTIONPAT              1059
#define IDC_MOTIONSENSTR                1060
#define IDC_MOTSENSITIVE                1061
#define IDC_PTZ_BOX                     1062
#define IDC_PTZ_ADDR                    1063
#define IDC_SPIN_PTZ_ADDR               1064
#define IDC_TABSENSOR                   1065
#define IDC_SENSORNAME                  1066
#define IDC_INVERTED                    1067
#define IDC_TIMEZONE                    1068
#define IDC_DAYLIGHT                    1069
#define IDC_SYN_TIME                    1070
#define IDC_DVR_TIME                    1071
#define IDC_CHECK_SIG0                  1080
#define IDC_CHECK_SIG1                  1081
#define IDC_CHECK_SIG2                  1082
#define IDC_CHECK_SIG3                  1083
#define IDC_CHECK_SIG4                  1084
#define IDC_CHECK_SIG5                  1085
#define IDC_CHECK_SIG6                  1086
#define IDC_CHECK_SIG7                  1087
#define IDC_CHECK_SIG8                  1088
#define IDC_CHECK_SIG9                  1089
#define IDC_CHECK_SIG10                 1090
#define IDC_CHECK_SIG11                 1091
#define IDC_CHECK_SIG12                 1092
#define IDC_CHECK_SIG13                 1093
#define IDC_CHECK_SIG14                 1094
#define IDC_CHECK_SIG15                 1095
#define IDC_CHECK_REC0                  1100
#define IDC_CHECK_REC1                  1101
#define IDC_CHECK_REC2                  1102
#define IDC_CHECK_REC3                  1103
#define IDC_CHECK_REC4                  1104
#define IDC_CHECK_REC5                  1105
#define IDC_CHECK_REC6                  1106
#define IDC_CHECK_REC7                  1107
#define IDC_CHECK_REC8                  1108
#define IDC_CHECK_REC9                  1109
#define IDC_CHECK_REC10                 1110
#define IDC_CHECK_REC11                 1111
#define IDC_CHECK_REC12                 1112
#define IDC_CHECK_REC13                 1113
#define IDC_CHECK_REC14                 1114
#define IDC_CHECK_REC15                 1115
#define IDC_CHECK_MOTION0               1120
#define IDC_CHECK_MOTION1               1121
#define IDC_CHECK_MOTION2               1122
#define IDC_CHECK_MOTION3               1123
#define IDC_CHECK_MOTION4               1124
#define IDC_CHECK_MOTION5               1125
#define IDC_CHECK_MOTION6               1126
#define IDC_CHECK_MOTION7               1127
#define IDC_CHECK_MOTION8               1128
#define IDC_CHECK_MOTION9               1129
#define IDC_CHECK_MOTION10              1130
#define IDC_CHECK_MOTION11              1131
#define IDC_CHECK_MOTION12              1132
#define IDC_CHECK_MOTION13              1133
#define IDC_CHECK_MOTION14              1134
#define IDC_CHECK_MOTION15              1135
#define IDC_LOCALTIMEZONENAME           1140
#define IDC_LOCALTIME                   1141
#define IDC_VERSION                     1142
#define IDC_SAVESETUP                   1143
#define IDC_LOADSETUP                   1144
#define IDC_COMMITSETUP                 1145
#define IDC_EDIT_PASSWORD1              1146
#define IDC_EDIT_PASSWORD2              1147
#define IDC_PTZ_TXT1                    1150
#define IDC_PTZ_TXT2                    1151
#define IDC_PTZ_TXT3                    1153
#define IDC_STATIC_CONTROLMODE          1154
#define IDC_STATIC_BITRATE              1155
#define IDC_GPSDISP                     1156

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2001
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2000
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
