//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by tvsviewer.rc
//
#define IDM_ABOUTBOX                    0x20
#define IDS_ABOUTBOX                    101
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_LOGIN                129
#define IDD_DIALOG_CALLTME              130
#define IDD_DVRCLIENT_DIALOG            132
#define IDR_MENU_MAIN                   134
#define IDR_MENU_POPUP                  135
#define IDD_DIALOG_SELECTDVR            138
#define IDD_DIALOG_CAPTURE              139
#define IDD_DIALOG_USER                 140
#define IDD_DIALOG_USERNEW              141
#define IDD_DIALOG_CHANGEPASSWORD       142
#define IDD_DIALOG_COPY                 143
#define IDD_DIALOG_VIDEOPASSWORD        144
#define IDD_DIALOG_REMOTEIP             145
#define IDD_DIALOG_USERPASSWORD         146
#define IDD_DIALOG_USBPASSWORD          147
#define IDI_PTZBALL                     148
#define IDD_ABOUTBOX1                   148
#define IDD_ABOUTBOX                    148
#define IDI_TVSVIEWER                   149
#define IDI_SMALL                       150
#define IDC_TVSVIEWER                   1000
#define IDC_USERNAME                    1001
#define IDC_PASSWORD                    1002
#define IDC_CODE                        1003
#define IDC_MONTHCALENDAR               1005
#define IDC_PREVIEW                     1006
#define IDC_PLAYBACK                    1007
#define IDC_SETUP                       1008
#define IDC_PLAYFILE                    1009
#define IDC_CAPTURE                     1010
#define IDC_SLIDER                      1011
#define IDC_GROUP_FUNCTION              1012
#define IDC_SAVEFILE                    1013
#define IDC_QUICKCAP                    1014
#define IDC_TIMEBEGIN                   1015
#define IDC_TIMEEND                     1016
#define IDC_TIME_SELBEGIN               1017
#define IDC_TIME_SELEND                 1018
#define IDC_GROUP_SAVEFILE              1019
#define IDC_SAVEFILE2                   1019
#define IDC_EXPORTJPG                   1019
#define IDC_MIXAUDIO                    1020
#define IDC_SLOW                        1021
#define IDC_BACKWARD                    1022
#define IDC_PAUSE                       1023
#define IDC_PLAY                        1024
#define IDC_FORWARD                     1025
#define IDC_FAST                        1026
#define IDC_STEP                        1027
#define IDC_MAP                         1028
#define IDC_PREV                        1029
#define IDC_NEXT                        1030
#define IDC_COMBO_TIMERANGE             1031
#define IDC_EXIT                        1032
#define IDC_USERS                       1033
#define IDC_PTZ_TELE                    1034
#define IDC_PTZ_WIDE                    1035
#define IDC_PTZ_FAR                     1036
#define IDC_PTZ_NEAR                    1037
#define IDC_PTZ_OPEN                    1038
#define IDC_PTZ_CLOSE                   1039
#define IDC_PTZ_SET                     1040
#define IDC_PTZ_CLEAR                   1041
#define IDC_PTZ_GOTO                    1042
#define IDC_PRESET_ID                   1043
#define IDC_SPIN_PTZ_PRESET             1044
#define IDC_GROUP_PTZ                   1046
#define IDC_STATIC_PLAYSPEED            1047
#define IDC_STATIC_TIMERANGE            1048
#define IDC_STATIC_PRESETID             1049
#define IDC_SMARTSERVER                 1051
#define IDC_LIST_DVRSERVER              1053
#define IDC_STATIC_PIC                  1056
#define IDC_BUTTON_PRINT                1057
#define IDC_BUTTON_SAVEFILE             1058
#define IDC_SLIDER_VOLUME               1059
#define IDC_BUTTON_NEWUSER              1060
#define IDC_BUTTON_DELUSER              1061
#define IDC_BUTTON_CHANGEPASSWORD       1062
#define IDC_LIST_USER                   1063
#define IDC_EDIT_USERNAME               1064
#define IDC_EDIT_PASSWORD               1065
#define IDC_EDIT_PASSWORD2              1066
#define IDC_RADIO_USER                  1067
#define IDC_RADIO_ADMIN                 1068
#define IDC_EDIT_OLDPASSWORD            1069
#define IDC_EDIT_NEWPASSWORD            1070
#define IDC_EDIT_CONFIIRMPASSWORD       1071
#define IDC_STATIC_USERNAME             1072
#define IDC_PROGRESS1                   1073
#define IDC_PROGRESS                    1073
#define IDC_STATIC_MSG                  1074
#define IDC_STATIC_PROGRESS             1075
#define IDC_STATIC_COMPANY              1076
#define IDC_STATIC_COPYRIGHT            1077
#define IDC_STATIC_VERSION              1078
#define IDC_STATIC_APP                  1079
#define IDC_STATIC_SCREEN               1081
#define IDC_BUTTON_OPENHARDDRIVE        1082
#define IDC_BUTTON_OPENREMOTE           1083
#define IDC_BUTTON_OPENHARDDRIVE2       1084
#define IDC_BUTTON_CLEANDISK            1084
#define IDC_DISCONNECT                  1086
#define IDC_LISTLIBRARY                 1087
#define IDC_EDIT_IPADDR                 1089
#define IDC_STATIC_SERVER               1093
#define IDC_STATIC_PLAYTIME             1094
#define IDC_PIC_SPEAKER_VOLUME          1095
#define IDC_BUTTON_PLAY                 1096
#define IDC_PIC_APPNAME                 1097
#define IDC_STATIC_GROUP_CUSTOMCLIP     1099
#define IDC_BUTTON2                     1101
#define IDC_BUTTON_TVSINFO              1107
#define IDC_STATIC_ENTERPASSWORD        1108
#define IDC_CHECK_CAM1                  1110
#define IDC_CHECK2                      1111
#define IDC_CHECK_CAM2                  1111
#define IDC_CHECK_CAM3                  1112
#define IDC_CHECK_CAM4                  1113
#define IDC_STATIC_SELCAM               1114
#define IDC_STATIC_QUICKTOOLS           1115
#define ID_FILE_CONNECT                 32772
#define ID_FILE_DISCONNECT              32773
#define ID_FILE_OPENLOCALDISK           32774
#define ID_FILE_OPENDVRFILE             32775
#define ID_FILE_CAPTUREPICTURE          32776
#define ID_FILE_EXIT                    32777
#define ID_EDIT_BEGINSELECTION          32778
#define ID_EDIT_ENDSELECTION            32779
#define ID_EDIT_EXPORTTO                32780
#define ID_PLAY_LIVEPREVIEW             32781
#define ID_PLAY_PLAYRECORDEDVIDEO       32782
#define ID_PLAY_SINGLEAUDIO             32783
#define ID_PLAY_MIXALLAUDIOCHANNEL      32784
#define ID_PLAY_PLAY                    32785
#define ID_PLAY_PLAY32786               32786
#define ID_PLAY_PAUSE                   32787
#define ID_PLAY_SINGLEFRAMEFORWARD      32788
#define ID_PLAY_FASTFORWARD             32789
#define ID_PLAY_SLOWFORWARD             32790
#define ID_PLAY_FASTBACKWARD            32791
#define ID_PLAY_PREV                    32792
#define ID_PLAY_NEXT                    32793
#define ID_PLAY_PREV32794               32794
#define ID_PLAY_NEXTDAY                 32795
#define ID_SETUP_DVRSETUP               32796
#define ID_SETUP_USERMANAGEMENT         32797
#define ID_SCREEN_1WINDOW               32798
#define ID_PTZ_CAMERAON                 32799
#define ID_PTZ_CAMERAOFF                32800
#define ID_PTZ_AUTOSCANON               32801
#define ID_PTZ_AUTOSCANOFF              32802
#define ID_PTZ_FLIP                     32803
#define ID_PTZ_ZEROPANPOSITION          32804
#define ID_PTZ_RESET                    32805
#define ID_PTZ_ZONESTART                32806
#define ID_ZONESTART_1                  32807
#define ID_ZONESTART_2                  32808
#define ID_ZONESTART_3                  32809
#define ID_ZONESTART_4                  32810
#define ID_ZONESTART_5                  32811
#define ID_ZONESTART_6                  32812
#define ID_ZONESTART_7                  32813
#define ID_ZONESTART_8                  32814
#define ID_PTZ_ZONEEND                  32815
#define ID_ZONEEND_1                    32816
#define ID_ZONEEND_2                    32817
#define ID_ZONEEND_3                    32818
#define ID_ZONEEND_4                    32819
#define ID_ZONEEND_5                    32820
#define ID_ZONEEND_6                    32821
#define ID_ZONEEND_7                    32822
#define ID_ZONEEND_8                    32823
#define ID_PTZ_ZONESCANON               32824
#define ID_PTZ_ZONESCANOFF              32825
#define ID_PTZ_PATTERNSTART             32826
#define ID_PATTERNSTART_1               32827
#define ID_PATTERNSTART_2               32828
#define ID_PATTERNSTART_3               32829
#define ID_PATTERNSTART_4               32830
#define ID_PATTERNSTART_5               32831
#define ID_PATTERNSTART_6               32832
#define ID_PATTERNSTART_7               32833
#define ID_PATTERNSTART_8               32834
#define ID_PTZ_PATTERNSTOP              32835
#define ID_PTZ_RUNPATTERN               32836
#define ID_RUNPATTERN_0                 32837
#define ID_RUNPATTERN_1                 32838
#define ID_RUNPATTERN_2                 32839
#define ID_RUNPATTERN_3                 32840
#define ID_RUNPATTERN_4                 32841
#define ID_RUNPATTERN_5                 32842
#define ID_RUNPATTERN_6                 32843
#define ID_RUNPATTERN_7                 32844
#define ID_RUNPATTERN_8                 32845
#define ID_PTZ_SETZONESPEED             32847
#define ID_SETZOOMSPEED_0               32848
#define ID_SETZOOMSPEED_1               32849
#define ID_SETZOOMSPEED_2               32850
#define ID_SETZOOMSPEED_3               32851
#define ID_PTZ_SETFOCUSSPEED            32852
#define ID_SETFOCUSSPEED_0              32853
#define ID_SETFOCUSSPEED_1              32854
#define ID_SETFOCUSSPEED_2              32855
#define ID_SETFOCUSSPEED_3              32856
#define ID_PTZ_AUTOFOCUSON              32857
#define ID_PTZ_AUTOFOCUSOFF             32858
#define ID_PTZ_AUTOIRISON               32859
#define ID_PTZ_AUTOIRISOFF              32860
#define ID_PREVIEWCHANNEL_RESETALLCHANNELS 32861
#define ID_PREVIEWCHANNEL_CLOSE         32862
#define ID_EVENTMARKER_SHOWALLMARKEDEVENTS 32863
#define ID_EVENTMARKER_CLEARALLMARKEDEVENTS 32864
#define ID_EVENTMARKER_CLEARMARKEDEVENTOFCURRENTDAY 32865
#define ID_SCREEN_CLOSE                 32866
#define ID_SCREEN_2X2                   32867
#define ID_SCREEN_2WINDOWSHORIZONTAL    32868
#define ID_SCREEN_2X3                   32869
#define ID_SCREEN_3X3                   32870
#define ID_SCREEN_4X4                   32871
#define ID_SCREEN_6WINDOWS              32872
#define ID_SCREEN_8WINDOWS              32873
#define ID_PLAYSOURCE_LIVEVIEW          32874
#define ID_PLAYSOURCE_PLAYARCH          32875
#define ID_PLAYSOURCE_PLAYFILE          32876
#define ID_PLAYSOURCE_PLAYSMARTSERVER   32877
#define ID_TVSINFORMATION_ACCESSHISTORY 32878
#define ID_TVSINFORMATION_CONFIGURATIONREPORT 32879
#define ID_TVSINFORMATION_SYSTEMLOG     32880
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32881
#define _APS_NEXT_CONTROL_VALUE         1116
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
