#ifndef _DIRECT_COMMON_H_
#define _DIRECT_COMMON_H_

#define IDM_TOGGLE_ON_TOP WM_USER + 1
#define DX_POSITION_CHANGE 0x1000

#define WM_TME_HIDE_MOUSE WM_APP
#define WM_TME_SHOW_MOUSE WM_APP + 1
#define WM_TME_CHANGE_TEXT WM_APP + 2
#define IDM_TOGGLE_ON_TOP WM_USER + 1
#define DX_POSITION_CHANGE 0x1000
#define DX_WALLPAPER_CHANGE 0x2000
#endif

